[package]
name = "browser"
version = "0.1.0"
license = "MIT"
edition = "2021"
authors = ["nikkehtine <nikkehtine@int.pl>"]

[dependencies]
engine = { path = "engine" }

[dependencies.sdl2]
version = "0.36.0"
default-features = false
features = ["ttf"]
